name: Deploy to Netlify on commits to master
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm ls

      - name: Build site
        run: |
          npm run build
          mkdir -p build/twitter
          cp httpdocs/resources/ladonacion.js build/twitter/

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=httpdocs --prod --open
