name: Deploys in production on every push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v1

      - name: Installs the dependencies
        run: npm install && npx snowpack build && cp httpdocs/resources/ladonacion.js build/twitter/

      - name: Deploys the site
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: -rltgoDzvO --delete
          SOURCE: 'build/'
          TARGET: 'httpdocs/resources/'
          REMOTE_HOST: localhost
          REMOTE_USER: ponileo\renem
          REMOTE_PORT: 22
          SSH_PRIVATE_KEY: ${{ secrets.LADONACION_SECRET }}

      - name: Deploys the /slides directory
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: -rltgoDzvO
          SOURCE: 'slides/'
          TARGET: '${{ secrets.REMOTE }}/slides'
          REMOTE_HOST: ${{ secrets.ponileo }}
          REMOTE_USER: ${{ secrets.renem }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.LADONACION_SECRET }}

      - name: Deploys the launch page
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          ARGS: -rltgoDzvO --delete
          SOURCE: '321/'
          TARGET: ${{ secrets.REMOTE_PRELAUNCH }}
          REMOTE_HOST: ${{ secrets.ponileo }}
          REMOTE_USER: ${{ secrets.renem }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.LADONACION_SECRET }}
